development:
  adapter: postgresql
  encoding: unicode
  database: project_management_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: project_management_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: project_management_production
  pool: 5
